// Create account
POST http://localhost:5248/api/accounts
Content-Type: application/json

{
    "AccountTypeId": 1,
    "Balance": 1000.00,
    "OverDraftLimit": 500.00
}

###
// Deposit
POST http://localhost:5248/api/accounts/deposit
Content-Type: application/json

{
    "accountId": "2",
    "amount": 10.10
}

###
// Withdraw
POST http://localhost:5248/api/accounts/withdraw
Content-Type: application/json

{
    "accountId": "1",
    "amount": 200
}
###
// Transfer
POST http://localhost:5248/api/accounts/transfer
Content-Type: application/json

{
    "accountId": 2,
    "TargetAccountId": 1,
    "amount": 400
}

###
// Get balance
GET http://localhost:5248/api/accounts/balance
Content-Type: application/json

{
    "accountId": 1
}